import localFont from 'next/font/local';
import './globals.css';
import CardContextProvider from './components/CardContext';
import { auth } from './lib/auth';
import { headers } from 'next/headers';
import Navbar from './components/Navbar';
import OptimistContextProvider from './components/OptimisticContextProvider';
import { getBoards } from './lib/helpers';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await auth?.api?.getSession({ headers: await headers() });
  const user = session?.user;
  const userId = session?.session?.userId;

  const boards = await getBoards(userId);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Navbar user={user} />
        <OptimistContextProvider boards={boards}>
          {children}
        </OptimistContextProvider>
      </body>
    </html>
  );
}
