import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { FaHome, FaSignInAlt } from 'react-icons/fa';
import CardContextProvider from './components/CardContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <nav className="flex justify-between p-1 bg-blue-600 items-center">
          <Link
            className="text-white bg-blue-400 p-1.5 rounded-sm text-xl"
            href="/"
          >
            <FaHome />
          </Link>
          <Link
            className="text-blue-200 tracking-wider font-semibold text-lg"
            href="/"
          >
            Trello
          </Link>
          <Link
            className="text-white bg-blue-400 p-1.5 rounded-sm text-xl"
            href="/login"
          >
            <FaSignInAlt />
          </Link>
        </nav>
        <CardContextProvider>{children}</CardContextProvider>
      </body>
    </html>
  );
}
